# .cpanel.yml
deployment:
  tasks:
    - export DEPLOYPATH="/home/$USER/public_html/"
    - /bin/rsync -a --delete \
        --exclude ".git" \
        --exclude ".github" \
        --exclude ".cpanel.yml" \
        ./ "$DEPLOYPATH"