# .cpanel.yml
deployment:
  tasks:
    - export DEPLOYPATH="/home/robbjsdz/public_html/"
    - /bin/rsync -a \
        --exclude ".git" \
        --exclude ".github" \
        --exclude ".cpanel.yml" \
        --exclude "README.md" \
        --exclude ".vscode" \
        ./ "$DEPLOYPATH"
